apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-pod-compliant
spec:
  containers:
  - name: node
    image: node:10-slim
    command: ['sh', '-c', 'sleep 3600']
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
---
apiVersion: v1
kind: Pod
metadata:
  name: malware-pod-compliant
spec:
  containers:
  - name: malware-container
    image: busybox
    command: ['sh', '-c', 'wget -O /tmp/eicar.com.txt http://www.eicar.org/download/eicar.com.txt && sleep 3600']
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    volumeMounts:
    - name: tmp-volume
      mountPath: /tmp
  volumes:
  - name: tmp-volume
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: fim-pod-volume
spec:
  containers:
  - name: fim-container
    image: busybox
    command: ['sh', '-c', 'touch /etc/config/fim-test-file && sleep 5 && echo "modified" >> /etc/config/fim-test-file && sleep 3600']
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    volumeMounts:
    - name: etc-config
      mountPath: /etc/config
  volumes:
  - name: etc-config
    emptyDir: {}