apiVersion: v1
kind: Pod
metadata:
  name: fim-deletion
spec:
  containers:
  - name: delete-container
    image: busybox
    # We wait 60s for baseline, then delete a critical file link (or simulation)
    command: ['sh', '-c', 'sleep 60 && rm /etc/hosts && sleep 3600']
    securityContext:
      runAsUser: 0
      readOnlyRootFilesystem: false
