apiVersion: v1
kind: Pod
metadata:
  name: fim-test-hosts
spec:
  containers:
  - name: fim-container
    image: busybox
    command: ['sh', '-c', 'sleep 60 && echo "1.2.3.4 attacker.com" >> /etc/hosts && sleep 3600']
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Pod
metadata:
  name: fim-test-cron
spec:
  containers:
  - name: fim-container
    image: busybox
    command: ['sh', '-c', 'sleep 60 && mkdir -p /etc/cron.d && echo "* * * * * root echo hello" > /etc/cron.d/malicious-job && sleep 3600']
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Pod
metadata:
  name: fim-test-apt
spec:
  containers:
  - name: fim-container
    image: busybox
    command: ['sh', '-c', 'sleep 60 && mkdir -p /etc/apt && echo "deb http://attacker.com/repo stable main" >> /etc/apt/sources.list && sleep 3600']
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Pod
metadata:
  name: fim-test-binary
spec:
  containers:
  - name: fim-container
    image: busybox
    command: ['sh', '-c', 'sleep 60 && chmod 777 /bin/sh && sleep 3600']
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Pod
metadata:
  name: fim-test-passwd
spec:
  containers:
  - name: fim-container
    image: busybox
    command: ['sh', '-c', 'sleep 60 && echo "hacker:x:0:0:hacker:/root:/bin/sh" >> /etc/passwd && sleep 3600']
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      readOnlyRootFilesystem: false
