apiVersion: v1
kind: Pod
metadata:
  name: malware-pod
spec:
  containers:
  - name: malware-container
    image: busybox
    command: ['sh', '-c', 'wget -O /tmp/eicar.com.txt http://www.eicar.org/download/eicar.com.txt && sleep 3600']
